### ISSUE TITLE
LICENSE question

### ISSUE THREAD

**Issue by a10y** [XiangpengHao/parquet-viewer#4]
Hey folks!

I stumbled across this project recently as I was investigating how to get Vortex working in WASM. One of the things I wanted to do was to show how to feed Vortex data into Datafusion so you can run queries directly in the browser. This codebase is really helpful and I wanted to use some sections of it, specifically around the Datafusion and the file_reader.

However, I noticed there's no LICENSE for this code, so I wanted to check how the authors feel about me reusing some of the code for my own open source project. If possible it'd be great to add a LICENSE file to the repo!

**Comment by XiangpengHao** [comment]
Here you go: https://github.com/XiangpengHao/parquet-viewer?tab=readme-ov-file#license

**Comment by a10y** [comment]
Thank you!
